# Generated by Django 4.2.4 on 2023-09-12 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_product_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='set_release',
            new_name='release',
        ),
    ]
