# Generated by Django 4.2.4 on 2023-09-17 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date_added',
            field=models.DateField(default=datetime.date(2023, 9, 15)),
        ),
    ]
