# Generated by Django 4.2.4 on 2023-10-03 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_item_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='color',
            field=models.CharField(choices=[('blue', 'Blue'), ('white', 'White'), ('yellow', 'Yellow'), ('purple', 'Purple'), ('green', 'Green'), ('black', 'Black')], default='blue', max_length=6),
        ),
    ]
