# Generated by Django 4.2.4 on 2023-10-03 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_item_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(choices=[('white', 'White'), ('lightgreen', 'Green'), ('lightgray', 'Black'), ('lightblue', 'Blue'), ('lightpurple', 'Purple'), ('lightyellow', 'Yellow')], default='lightblue', max_length=11),
        ),
    ]
