# Generated by Django 4.2.4 on 2023-10-03 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_item_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(choices=[('Black', 'Black'), ('White', 'White'), ('Purple', 'Purple'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow')], default='lightblue', max_length=11),
        ),
    ]
