# Generated by Django 4.2.4 on 2023-10-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_item_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(choices=[('Black', 'Black'), ('Blue', 'Blue'), ('White', 'White'), ('Red', 'Red'), ('Purple', 'Purple'), ('Yellow', 'Yellow'), ('Green', 'Green')], max_length=11),
        ),
    ]
