# Generated by Django 4.2.5 on 2023-11-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_item_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(choices=[('Purple', 'Purple'), ('Blue', 'Blue'), ('Yellow', 'Yellow'), ('Black', 'Black'), ('Red', 'Red'), ('White', 'White'), ('Green', 'Green')], max_length=11),
        ),
    ]
